apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ue95x38pg-nodejs 
  janus-idp.io/tekton: ue95x38pg-nodejs
  backstage.io/kubernetes-id: ue95x38pg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ue95x38pg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  