apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ue95x38pg-nodejs
  janus-idp.io/tekton: ue95x38pg-nodejs
  backstage.io/kubernetes-id: ue95x38pg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ue95x38pg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
