apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ue95x38pg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ue95x38pg-nodejs 
  name: ue95x38pg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ue95x38pg-nodejs 
